version: '3.8'

services:
  amc-container:
    build: .
    container_name: amc-vm
    ports:
      - "5900:5900"
    volumes:
      - ./home:/root
    environment:
      - DISPLAY=:0
      - LC_ALL=fr_FR.UTF-8
      - LANG=fr_FR.UTF-8
      - LANGUAGE=fr_FR.UTF-8
      - VNC_PASSWORD=${VNC_PASSWORD:-monpasswordsecret}
    command: sh -c 'x11vnc -passwd ${VNC_PASSWORD:-monpasswordsecret} -create -bg -reopen -forever -env FD_PROG=/usr/bin/openbox -afteraccept "uxterm -hold -e auto-multiple-choice & uxterm &" && sleep infinity'